# PROMETHEUS
- name: Creating a directory (where the downloaded files will be stored)
  tags: directory
  file:
    path: ~/prometheus
    state: directory
  
- name: Downloading and extracting Prometheus
  tags: source
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.39.1/prometheus-2.39.1.linux-amd64.tar.gz
    dest: ~/prometheus
    remote_src: yes
    mode: 0777
    owner: root
    group: root

- name: Stopping the service 
  service:
    name: prometheus
    state: stopped 

- name: Adding the Prometheus executables to a PATH
  tags: executables
  shell: | 
    cd ~/prometheus/prometheus*
    cp -r . /usr/local/bin/prometheus
- name: Copying the Prometheus service file
  tags: servicefile
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 777

- name: Making sure that httpd is started and enabled
  tags: serviceon
  service:
    name: prometheus
    state: restarted
    enabled: true

# GRAFANA
- name: Installing dependencies
  apt:
    name:  
      - apt-transport-https
      - software-properties-common 
      - wget
    state: latest

- name: Adding Grafana Repo
  shell: |
    echo "deb [signed-by=/usr/share/keyrings/grafana.key] https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list

- name: Updating the repo and isntalling grafana
  apt:
    name:
      - grafana
    update_cache: true
    state: lastest

- name: Reloading the daemon
  shell: |
    sudo systemctl daemon-reload

- name: Sarting and enabling the service
  service:
    name: grafana-server
    state: restarted
    enabled: true

# INFLUXDB
- name: Adding influxdb in the repo
  shell: |
    echo "deb https://repos.influxdata.com/ubuntu focal stable" | sudo tee /etc/apt/sources.list.d/influxdb.list

- name: Updating and installing influxdb
  apt:
    name:
      - influxdb
    update_cache: true

- name: Starting and enabling the service
  service:
    name: influxdb
    state: restarted
    enabled: true




